<%@ Page language="c#" %>
<script runat="server" language="c#">
	
		 /****
		Message contains diagnostic information that can be helpful for determing
		problems with an installation. WARNING: content in the debug diagnostic
		can provide sensitive information about the provider installation.*/
		public const string DIAG_DEBUG = "debug";
		 /****
		Message contains information about the status of the provider service or the
		recent operation.*/
		public const string DIAG_INFO = "info";
		 /****
		Message contains information warning that the operation of the provider
		service may be incorrect, but no particular error was detected.*/
		public const string DIAG_WARN = "warn";
		 /****
		An error occurred. The results that were generated should not be trusted as
		the content may be incorrect.*/
		public const string DIAG_ERROR = "error";
		 /****
		Normal operation of the provider services was compromised and execution of the
		request could not be completed.*/
		public const string DIAG_FATAL = "fatal";
		 /****
		Displays a debug message.*/
		public const string DC_DEBUG_MSG = "DEBUG_MESSAGE";
		 /****
		Indicates that a certain capability is not supported.*/
		public const string DC_UNSUPPORTED_CAPABILITY = "UNSUPPORTED_CAPABILITY";
		 /****
		Indicates that an unknown/unsupported component was found in the response structure definition.*/
		public const string DC_UNSUPPORTED_SCHEMA_COMPONENT = "UNSUPPORTED_SCHEMA_COMPONENT";
		 /****
		Indicates that a certain concept is not mapped.*/
		public const string DC_UNMAPPED_CONCEPT = "UNMAPPED_CONCEPT";
		 /****
		Indicates that a certain environment variable is unknown.*/
		public const string DC_UNKNOWN_VARIABLE = "UNKNOWN_VARIABLE";
		 /****
		Indicates that a certain concept used in the filter is not searchable.*/
		public const string DC_UNSEARCHABLE_CONCEPT = "UNSEARCHABLE_CONCEPT";
		 /****
		Indicates that the request is invalid.*/
		public const string DC_INVALID_REQUEST = "INVALID_REQUEST";
		 /****
		Indicates that the request is invalid.*/
		public const string DC_TRUNCATED_RESPONSE = "TRUNCATED_RESPONSE";
		 /****
		Indicates that the output model provided is not supported.*/
		public const string DC_UNSUPPORTED_OUTPUT_MODEL = "UNSUPPORTED_OUTPUT_MODEL";
		 /****
		Indicates some problem in the response structure.*/
		public const string DC_RESPONSE_STRUCTURE_ISSUE = "RESPONSE_STRUCTURE_ISSUE";
		 /****
		An invalid filter was provided in the request.*/
		public const string DC_INVALID_FILTER = "INVALID_FILTER";
		 /****
		Indicates that a parameter is missing.*/
		public const string DC_MISSING_PARAMETER = "MISSING_PARAMETER";
		 /****
		Indicates a mismatch between the version of a software or component that is known
		to work with TapirDotNET and the current software or component installed.*/
		public const string DC_VERSION_MISMATCH = "VERSION_MISMATCH";
		 /****
		Indicates an input/output error (reading from or writting to the file system).*/
		public const string DC_IO_ERROR = "IO_ERROR";
		 /****
		Indicates an error when parsing an XML string or file.*/
		public const string DC_XML_PARSE_ERROR = "XML_PARSE_ERROR";
		 /****
		Indicates an error in the server configuration.*/
		public const string DC_SERVER_SETUP_ERROR = "SERVER_SETUP_ERROR";
		 /****
		There was a communication problem between the script and the
		database.*/
		public const string DC_DB_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR";
		 /****
		Reports an error message that was generated by the database driver. The
		text of the message is the error message provided by the database interface.*/
		public const string DC_DATABASE_ERROR = "DATABASE_ERROR";
		 /****
		A query term was not in the expected form for the searchable concept.*/
		public const string DC_INVALID_FILTER_TERM = "INVALID_FILTER_TERM";
		 /****
		The requested resource was not available on the data provider.*/
		public const string DC_RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND";
		 /****
		The configuration information for the provider could not be found or loaded, and hence
		the requested operation could not be completed.*/
		public const string DC_CONFIG_FAILURE = "CONFIGURATION_FAILURE";
		 /****
		Problem occured when opening or writing to a log file.*/
		public const string DC_LOG_ERROR = "LOG_ERROR";
		 /****
		A catch-all diagnostic for where no other appropriate category is available.*/
		public const string DC_GENERAL_ERROR = "GENERAL_ERROR";
		 /****
		The specified library is not available.*/
		public const string DC_MISSING_LIBRARY = "MISSING_LIBRARY";
		 /****
		A float value indicating the number of seconds to produce the response.*/
		public const string DC_DURATION = "DURATION";
		 /****
		A validation error occurred after submitting a form during configuration.*/
		public const string CFG_DATA_VALIDATION_ERROR = "DATA_VALIDATION_ERROR";
		 /****
		An error occurred during the UDDI registration process.*/
		public const string CFG_UDDI_ERROR = "UDDI_ERROR";
		 /****
		An error (probably during development) prevented the configurator to work properly.*/
		public const string CFG_INTERNAL_ERROR = "INTERNAL_ERROR";
</script>
<%
		 /*******************************************************************
		TapirDotNET diagnostic codes generated from tapir_errors.xml
		*******************************************************************/
		
		////
		//Diagnostic Levels
		
		
		
		
		
		
		
		
		
		
		
		
		////
		//Diagnostic Codes
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
	%>
